# src/agents/schemas.py
from typing import Optional

from pydantic import BaseModel, Field


class TriageOutput(BaseModel):
    """Structured output enforcing how the Triage Agent must respond."""

    severity: str = Field(..., description="Must be 'CRITICAL', 'WARNING', or 'NOISE'")
    impacted_service: str = Field(
        ..., description="The name of the failing microservice"
    )
    summary: str = Field(..., description="A 1-sentence summary of the alert")
    next_step: str = Field(..., description="Must be 'INVESTIGATE' or 'SILENCE'")


class RemediationArtifacts(BaseModel):
    """Strict schema for code generated by the Execution Agent."""

    kubernetes_yaml: Optional[str] = Field(
        None, description="Patched Kubernetes deployment YAML"
    )
    terraform_hcl: Optional[str] = Field(None, description="Patched Terraform HCL")
    pr_title: str = Field(..., description="GitHub PR Title")
    pr_body: str = Field(
        ..., description="GitHub PR Description detailing root cause and fix"
    )


class ReviewFeedback(BaseModel):
    """Schema for Human-in-the-Loop feedback."""

    status: str = Field(
        ..., description="Must be 'approved', 'rejected', or 'revision'"
    )
    comments: Optional[str] = Field(
        None, description="Human feedback if rejected or revision requested"
    )
