import asyncio
import json
import logging
from aiokafka import AIOKafkaConsumer

from src.core.config import settings
from src.agents.graph import app as agent_app

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("worker")

async def consume_alerts():
    # FIX 1: Align the topic string with the FastAPI producer
    # Recommended: Replace with settings.KAFKA_INCIDENTS_TOPIC
    consumer = AIOKafkaConsumer(
        'incidents',
        bootstrap_servers=settings.KAFKA_BOOTSTRAP_SERVERS,
        group_id="autoresolve-ai-swarm",
        auto_offset_reset="earliest",      # Critical: Start from beginning
        enable_auto_commit=True,           # Ensure we commit offsets
        session_timeout_ms=10000           # Prevent aggressive rebalancing
    )
    
    await consumer.start()
    logger.info("🟢 AI Worker successfully connected to Kafka. Listening for alerts...")
    
    try:
        async for msg in consumer:
            payload = json.loads(msg.value.decode('utf-8'))
            
            # Extract the idempotency hash generated by the API Gateway
            incident_id = payload.get('tracking_id', 'INC-UNKNOWN')
            logger.info(f"🚨 KAFKA ALERT RECEIVED: Processing Incident {incident_id}")
            
            initial_state = {
                "incident_id": incident_id,
                "alert_payload": payload,
                "logs": [],
                "proposed_fix": "",
                "messages": []
            }
            
            thread_config = {"configurable": {"thread_id": incident_id}}
            
            logger.info(f"🧠 Invoking LangGraph Swarm for {incident_id}...")
            
            # FIX 2 & 3: Utilize `astream()` inside an `async for` loop to prevent Event Loop Starvation
            async for event in agent_app.astream(initial_state, config=thread_config):
                for node_name, node_state in event.items():
                    logger.info(f"✅ Node Completed: [{node_name}]")
            
            # FIX 4: Use asynchronous state retrieval to prevent I/O blocking
            state = await agent_app.aget_state(thread_config)
            if state.next:
                logger.info(f"⏸️ GRAPH PAUSED. Next node in queue: {state.next}")
                logger.info(f"👨‍💻 Waiting for Human-in-the-Loop approval for Thread: {incident_id}")
                
    finally:
        await consumer.stop()

if __name__ == "__main__":
    asyncio.run(consume_alerts())